### ISSUE TITLE
[TV][Searcher] - Make searcher extendable for multiple media types

### ISSUE THREAD

**Issue by RuudBurger** [RuudBurger/CouchPotatoServer#2020]

**Comment by k0ekk0ek** [comment]
The searchers for movies, seasons and episodes have been merged into the base searcher because they basically all implement the same functionality. Search for a media type, get the profile, check if it has been released etc. The more generic searcher now simply invokes type specific methods to get the profile, check if it could be released etc. This was done in the following commit: #5188.

I think this issue can be closed @RuudBurger. It's likely that the code will undergo more changes before show support is considered stable, but the basic functionality is done.
